version: '3.8'

services:
  mqtt: 
    image: thmork/st4-mqtt:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
  
  st4-agv:
    image: thmork/st4-agv:latest
    restart: always
    ports:
      - 8082:80

  st4-warehouse:
    image: thmork/st4-warehouse:latest
    restart: always
    ports:
      - 8081:80

  st4-assemblystation:
    image: thmork/st4-assemblystation:latest
    restart: always
    environment:
      MQTT_TCP_CONNECTION_HOST: "mqtt"
      MQTT_TCP_CONNECTION_PORT: 1883
  
  st4-mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

